
package com.xmdj;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-30T15:48:24.389+08:00
 * Generated source version: 3.3.3
 *
 */
public final class CommonService_CommonServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.WebService.demo.example.com", "CommonService");

    private CommonService_CommonServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CommonService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CommonService_Service ss = new CommonService_Service(wsdlURL, SERVICE_NAME);
        CommonService port = ss.getCommonServiceImplPort();

        {
        System.out.println("Invoking helloWorlda...");
        com.xmdj.HelloWorlda _helloWorlda_parameters = null;
        com.xmdj.HelloWorldaResponse _helloWorlda__return = port.helloWorlda(_helloWorlda_parameters);
        System.out.println("helloWorlda.result=" + _helloWorlda__return);


        }
        {
        System.out.println("Invoking helloWorld...");
        java.lang.String _helloWorld_helloName = "";
        java.lang.String _helloWorld__return = port.helloWorld(_helloWorld_helloName);
        System.out.println("helloWorld.result=" + _helloWorld__return);


        }

        System.exit(0);
    }

}
